package Interface;

import Controller.FuncionarioController;
import Controller.FuncionarioTable;

public class CadastrarFuncionarios extends javax.swing.JFrame {

    private FuncionarioController controller;
    private FuncionarioTable tableController;

    public CadastrarFuncionarios() {
        initComponents();
        controller = new FuncionarioController();
        tableController = new FuncionarioTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        nomeCliente6 = new javax.swing.JLabel();
        campoNomeCliente6 = new javax.swing.JTextField();
        cpfCliente6 = new javax.swing.JLabel();
        campoCpfCliente6 = new javax.swing.JTextField();
        sexoCliente6 = new javax.swing.JLabel();
        btnFemininoC6 = new javax.swing.JRadioButton();
        btnMasculinoC6 = new javax.swing.JRadioButton();
        dataNascCliente6 = new javax.swing.JLabel();
        campoDataNascC6 = new javax.swing.JTextField();
        btnSalvarE6 = new javax.swing.JButton();
        btnCancelarC6 = new javax.swing.JButton();
        enderecoCliente6 = new javax.swing.JLabel();
        campoEnderecoC6 = new javax.swing.JTextField();
        telefoneCliente6 = new javax.swing.JLabel();
        campoCidadeCliente6 = new javax.swing.JTextField();
        cidadeCliente6 = new javax.swing.JLabel();
        ufCliente6 = new javax.swing.JLabel();
        comboUfC6 = new javax.swing.JComboBox();
        campoTelefoneC6 = new javax.swing.JTextField();
        btnBuscaCli6 = new javax.swing.JButton();
        btnExcluirC6 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        nomeFuncionario = new javax.swing.JLabel();
        campoNomeFuncionario = new javax.swing.JTextField();
        cpfFuncionario = new javax.swing.JLabel();
        campoCpfFuncionario = new javax.swing.JTextField();
        sexoFuncionario = new javax.swing.JLabel();
        btnFemininoF = new javax.swing.JRadioButton();
        btnMasculinoF = new javax.swing.JRadioButton();
        dataNascFuncionario = new javax.swing.JLabel();
        campoDataNascF = new javax.swing.JTextField();
        enderecoFuncionario = new javax.swing.JLabel();
        campoEnderecoF = new javax.swing.JTextField();
        telefoneFuncionario = new javax.swing.JLabel();
        campoCidadeF = new javax.swing.JTextField();
        cidadeFuncionario = new javax.swing.JLabel();
        ufFuncionario = new javax.swing.JLabel();
        comboUfF = new javax.swing.JComboBox();
        campoTelefoneF = new javax.swing.JTextField();
        btnSalvarF = new javax.swing.JButton();
        numeroEFuncionario = new javax.swing.JLabel();
        campoNumeroEF = new javax.swing.JTextField();
        complementoFuncionario = new javax.swing.JLabel();
        campoComplementoF = new javax.swing.JTextField();
        btnBuscarF = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel11.setToolTipText("");
        jPanel11.setName(""); // NOI18N

        nomeCliente6.setText("Nome:");

        cpfCliente6.setText("CPF:");

        sexoCliente6.setText("Sexo:");

        btnFemininoC6.setBackground(new java.awt.Color(153, 153, 153));
        btnFemininoC6.setText("Feminino");

        btnMasculinoC6.setBackground(new java.awt.Color(153, 153, 153));
        btnMasculinoC6.setText("Masculino");

        dataNascCliente6.setText("Data de Nascimento: ");

        btnSalvarE6.setText("Atualizar");
        btnSalvarE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarE6ActionPerformed(evt);
            }
        });

        btnCancelarC6.setText("Cancelar");
        btnCancelarC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarC6ActionPerformed(evt);
            }
        });

        enderecoCliente6.setText("Endereço:");

        telefoneCliente6.setText("Telefone:");

        cidadeCliente6.setText("Cidade:");

        ufCliente6.setText("UF:");

        comboUfC6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        comboUfC6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        comboUfC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUfC6ActionPerformed(evt);
            }
        });

        btnBuscaCli6.setText("Buscar");

        btnExcluirC6.setText("Excluir");
        btnExcluirC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirC6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(dataNascCliente6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoDataNascC6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeCliente6)
                                .addComponent(cpfCliente6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNomeCliente6, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(campoCpfCliente6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(cidadeCliente6)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCidadeCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnBuscaCli6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(btnSalvarE6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btnCancelarC6)))))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecoCliente6)
                            .addComponent(ufCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefoneCliente6)
                            .addComponent(sexoCliente6))
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(btnFemininoC6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMasculinoC6))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboUfC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoEnderecoC6, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(campoTelefoneC6)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnExcluirC6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCliente6)
                    .addComponent(campoNomeCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoCliente6)
                    .addComponent(btnFemininoC6)
                    .addComponent(btnMasculinoC6))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enderecoCliente6)
                        .addComponent(campoEnderecoC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCpfCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cpfCliente6)))
                .addGap(29, 29, 29)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDataNascC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufCliente6)
                    .addComponent(comboUfC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascCliente6))
                .addGap(27, 27, 27)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cidadeCliente6)
                        .addComponent(campoCidadeCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefoneCliente6)
                        .addComponent(campoTelefoneC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarE6)
                    .addComponent(btnCancelarC6)
                    .addComponent(btnBuscaCli6)
                    .addComponent(btnExcluirC6))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Funcionários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel13.setToolTipText("");
        jPanel13.setName(""); // NOI18N

        nomeFuncionario.setText("Nome:");

        cpfFuncionario.setText("CPF:");

        sexoFuncionario.setText("Sexo:");

        btnFemininoF.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup2.add(btnFemininoF);
        btnFemininoF.setText("Feminino");

        btnMasculinoF.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup2.add(btnMasculinoF);
        btnMasculinoF.setText("Masculino");

        dataNascFuncionario.setText("Data de Nascimento: ");

        enderecoFuncionario.setText("Endereço:");

        telefoneFuncionario.setText("Telefone:");

        cidadeFuncionario.setText("Cidade:");

        ufFuncionario.setText("UF:");

        comboUfF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        comboUfF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        comboUfF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUfFActionPerformed(evt);
            }
        });

        btnSalvarF.setText("Salvar");
        btnSalvarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFActionPerformed(evt);
            }
        });

        numeroEFuncionario.setText("Número:");

        complementoFuncionario.setText("Complemento:");

        btnBuscarF.setText("Buscar");
        btnBuscarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addComponent(dataNascFuncionario)
                            .addGap(10, 10, 10)
                            .addComponent(campoDataNascF, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomeFuncionario)
                                .addComponent(cpfFuncionario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoNomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(campoCpfFuncionario))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(telefoneFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(174, 174, 174)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enderecoFuncionario)
                                    .addComponent(sexoFuncionario))
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(18, 22, Short.MAX_VALUE)
                                        .addComponent(btnFemininoF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMasculinoF)
                                        .addGap(90, 90, 90))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoEnderecoF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(numeroEFuncionario)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ufFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadeFuncionario))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboUfF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(campoNumeroEF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(complementoFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoComplementoF)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnSalvarF, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnBuscarF)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFuncionario)
                    .addComponent(campoNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoFuncionario)
                    .addComponent(btnFemininoF)
                    .addComponent(btnMasculinoF))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enderecoFuncionario)
                        .addComponent(campoEnderecoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cpfFuncionario)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroEFuncionario)
                            .addComponent(campoNumeroEF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complementoFuncionario)
                            .addComponent(campoComplementoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboUfF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ufFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidadeFuncionario)
                            .addComponent(campoCidadeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(campoDataNascF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNascFuncionario)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefoneFuncionario)
                            .addComponent(campoTelefoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarF)
                            .addComponent(btnBuscarF))
                        .addGap(22, 22, 22))))
        );

        jPanel14.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO PI2 250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(227, 227, 227))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarE6ActionPerformed

    }//GEN-LAST:event_btnSalvarE6ActionPerformed

    private void btnCancelarC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarC6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarC6ActionPerformed

    private void comboUfC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUfC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUfC6ActionPerformed

    private void btnExcluirC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirC6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirC6ActionPerformed

    private void comboUfFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUfFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUfFActionPerformed

    private void btnSalvarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFActionPerformed
        String nomeFuncionario;
        int cpfFuncionario;
        boolean sexoFuncionario = false;
        int datanFuncionario;
        String enderecoFuncionario;
        int numeroEFuncionario;
        String complementoFuncionario;
        String cidadeFuncionario;
        String ufFuncionario;
        int telefoneFuncionario;

        nomeFuncionario = (campoNomeFuncionario.getText());
        cpfFuncionario = Integer.parseInt(campoCpfFuncionario.getText());
        datanFuncionario = Integer.parseInt(campoDataNascF.getText());
        enderecoFuncionario = (campoEnderecoF.getText());
        numeroEFuncionario = Integer.parseInt(campoNumeroEF.getText());
        complementoFuncionario = (campoComplementoF.getText());
        cidadeFuncionario = (campoCidadeF.getText());
        ufFuncionario = (comboUfF.getActionCommand());
        telefoneFuncionario = Integer.parseInt(campoTelefoneF.getText());

        controller.salvarFuncionario(nomeFuncionario, cpfFuncionario, sexoFuncionario, datanFuncionario,
                enderecoFuncionario, numeroEFuncionario, complementoFuncionario, cidadeFuncionario, ufFuncionario, telefoneFuncionario);

    }//GEN-LAST:event_btnSalvarFActionPerformed

    private void btnBuscarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFActionPerformed
         new TabelaFuncionario().setVisible(true);
    }//GEN-LAST:event_btnBuscarFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCli6;
    private javax.swing.JButton btnBuscarF;
    private javax.swing.JButton btnCancelarC6;
    private javax.swing.JButton btnExcluirC6;
    private javax.swing.JRadioButton btnFemininoC6;
    private javax.swing.JRadioButton btnFemininoF;
    private javax.swing.JRadioButton btnMasculinoC6;
    private javax.swing.JRadioButton btnMasculinoF;
    private javax.swing.JButton btnSalvarE6;
    private javax.swing.JButton btnSalvarF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoCidadeCliente6;
    private javax.swing.JTextField campoCidadeF;
    private javax.swing.JTextField campoComplementoF;
    private javax.swing.JTextField campoCpfCliente6;
    private javax.swing.JTextField campoCpfFuncionario;
    private javax.swing.JTextField campoDataNascC6;
    private javax.swing.JTextField campoDataNascF;
    private javax.swing.JTextField campoEnderecoC6;
    private javax.swing.JTextField campoEnderecoF;
    private javax.swing.JTextField campoNomeCliente6;
    private javax.swing.JTextField campoNomeFuncionario;
    private javax.swing.JTextField campoNumeroEF;
    private javax.swing.JTextField campoTelefoneC6;
    private javax.swing.JTextField campoTelefoneF;
    private javax.swing.JLabel cidadeCliente6;
    private javax.swing.JLabel cidadeFuncionario;
    private javax.swing.JComboBox comboUfC6;
    private javax.swing.JComboBox comboUfF;
    private javax.swing.JLabel complementoFuncionario;
    private javax.swing.JLabel cpfCliente6;
    private javax.swing.JLabel cpfFuncionario;
    private javax.swing.JLabel dataNascCliente6;
    private javax.swing.JLabel dataNascFuncionario;
    private javax.swing.JLabel enderecoCliente6;
    private javax.swing.JLabel enderecoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel nomeCliente6;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JLabel numeroEFuncionario;
    private javax.swing.JLabel sexoCliente6;
    private javax.swing.JLabel sexoFuncionario;
    private javax.swing.JLabel telefoneCliente6;
    private javax.swing.JLabel telefoneFuncionario;
    private javax.swing.JLabel ufCliente6;
    private javax.swing.JLabel ufFuncionario;
    // End of variables declaration//GEN-END:variables
}
