/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

/**
 *
 * @author Ouro Conrado
 */
public class PDV extends javax.swing.JFrame {

    /**
     * Creates new form PDV
     */
    public PDV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnNovaVenda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuConfig = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenu();
        BtnNovoCli = new javax.swing.JMenuItem();
        BtnAtualizarDCli = new javax.swing.JMenuItem();
        MenuProd = new javax.swing.JMenu();
        BtnNovoProd = new javax.swing.JMenuItem();
        BtnAtualizarProd = new javax.swing.JMenuItem();
        MenuFuncionario = new javax.swing.JMenu();
        BtnNovoFunc = new javax.swing.JMenuItem();
        BtnAtualizarFunc = new javax.swing.JMenuItem();
        MenuCons = new javax.swing.JMenu();
        MenuConsultaCli = new javax.swing.JMenu();
        BtnConsPCodCli = new javax.swing.JMenuItem();
        BtnConsPNomeCli = new javax.swing.JMenuItem();
        MenuConsultaProd = new javax.swing.JMenu();
        BtnConsPCodProd = new javax.swing.JMenuItem();
        BtnConsPNomeProd = new javax.swing.JMenuItem();
        MenuConsultaFunc = new javax.swing.JMenu();
        BtnConsPCodFunc = new javax.swing.JMenuItem();
        BtnConsPNomeFunc = new javax.swing.JMenuItem();
        MenuRelatorioVendas = new javax.swing.JMenu();
        BtnConsAnaliticoRV = new javax.swing.JMenuItem();
        BtnConsSinteticoRV = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        MMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/LOGO PI2 250.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        BtnNovaVenda.setText("NOVA VENDA");
        BtnNovaVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(BtnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        MenuConfig.setText("Cadastros");

        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/cliente.png"))); // NOI18N
        MenuCliente.setText("Cliente");

        BtnNovoCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/novocliente.png"))); // NOI18N
        BtnNovoCli.setText("NovoCliente");
        BtnNovoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoCliActionPerformed(evt);
            }
        });
        MenuCliente.add(BtnNovoCli);

        BtnAtualizarDCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/atualizar.png"))); // NOI18N
        BtnAtualizarDCli.setText("AtualizarDadosCliente");
        BtnAtualizarDCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarDCliActionPerformed(evt);
            }
        });
        MenuCliente.add(BtnAtualizarDCli);

        MenuConfig.add(MenuCliente);

        MenuProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/novoproduto.png"))); // NOI18N
        MenuProd.setText("Produto");

        BtnNovoProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/novoproduto.png"))); // NOI18N
        BtnNovoProd.setText("Novo Produto");
        BtnNovoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoProdActionPerformed(evt);
            }
        });
        MenuProd.add(BtnNovoProd);

        BtnAtualizarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/atualizar.png"))); // NOI18N
        BtnAtualizarProd.setText("Atualizar Produto");
        BtnAtualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarProdActionPerformed(evt);
            }
        });
        MenuProd.add(BtnAtualizarProd);

        MenuConfig.add(MenuProd);

        MenuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/funcionario.png"))); // NOI18N
        MenuFuncionario.setText("Funcionário");

        BtnNovoFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/novofun.png"))); // NOI18N
        BtnNovoFunc.setText("NovoFuncionário");
        BtnNovoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoFuncActionPerformed(evt);
            }
        });
        MenuFuncionario.add(BtnNovoFunc);

        BtnAtualizarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/atualizar.png"))); // NOI18N
        BtnAtualizarFunc.setText("AtualizarFuncionário");
        BtnAtualizarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarFuncActionPerformed(evt);
            }
        });
        MenuFuncionario.add(BtnAtualizarFunc);

        MenuConfig.add(MenuFuncionario);

        jMenuBar1.add(MenuConfig);

        MenuCons.setText("Cosultar");

        MenuConsultaCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/cclie.png"))); // NOI18N
        MenuConsultaCli.setText("Consultar Cliente");

        BtnConsPCodCli.setText("PeloCódigo");
        BtnConsPCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsPCodCliActionPerformed(evt);
            }
        });
        MenuConsultaCli.add(BtnConsPCodCli);

        BtnConsPNomeCli.setText("PeloNome");
        BtnConsPNomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsPNomeCliActionPerformed(evt);
            }
        });
        MenuConsultaCli.add(BtnConsPNomeCli);

        MenuCons.add(MenuConsultaCli);

        MenuConsultaProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/cprod.png"))); // NOI18N
        MenuConsultaProd.setText("Consultar Produto");

        BtnConsPCodProd.setText("PeloCódigo");
        MenuConsultaProd.add(BtnConsPCodProd);

        BtnConsPNomeProd.setText("PeloNome");
        MenuConsultaProd.add(BtnConsPNomeProd);

        MenuCons.add(MenuConsultaProd);

        MenuConsultaFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/cfun.png"))); // NOI18N
        MenuConsultaFunc.setText("Consultar Funcionario");

        BtnConsPCodFunc.setText("PeloCodigo");
        MenuConsultaFunc.add(BtnConsPCodFunc);

        BtnConsPNomeFunc.setText("PeloNome");
        MenuConsultaFunc.add(BtnConsPNomeFunc);

        MenuCons.add(MenuConsultaFunc);

        MenuRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/relatório.png"))); // NOI18N
        MenuRelatorioVendas.setText("Relatorio de Vendas");

        BtnConsAnaliticoRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/relatório.png"))); // NOI18N
        BtnConsAnaliticoRV.setText("Analítico");
        BtnConsAnaliticoRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsAnaliticoRVActionPerformed(evt);
            }
        });
        MenuRelatorioVendas.add(BtnConsAnaliticoRV);

        BtnConsSinteticoRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/relatório.png"))); // NOI18N
        BtnConsSinteticoRV.setText("Sintético");
        BtnConsSinteticoRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsSinteticoRVActionPerformed(evt);
            }
        });
        MenuRelatorioVendas.add(BtnConsSinteticoRV);

        MenuCons.add(MenuRelatorioVendas);

        jMenuBar1.add(MenuCons);

        MenuSair.setText("Sair");

        MMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prototipo/exit.png"))); // NOI18N
        MMenuSair.setText("Sair");
        MMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMenuSairActionPerformed(evt);
            }
        });
        MenuSair.add(MMenuSair);

        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNovoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoCliActionPerformed
     new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_BtnNovoCliActionPerformed

    private void BtnAtualizarDCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarDCliActionPerformed
      new EditarCliente().setVisible(true);
    }//GEN-LAST:event_BtnAtualizarDCliActionPerformed

    private void BtnAtualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarProdActionPerformed
        new EditarProd().setVisible(true);
    }//GEN-LAST:event_BtnAtualizarProdActionPerformed

    private void BtnNovoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoFuncActionPerformed
        new CadastrarFuncionários().setVisible(true);
    }//GEN-LAST:event_BtnNovoFuncActionPerformed

    private void BtnConsPNomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsPNomeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsPNomeCliActionPerformed

    private void BtnConsPCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsPCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConsPCodCliActionPerformed

    private void MMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMenuSairActionPerformed
        new Tela_Inicial().setVisible(true); 
    }//GEN-LAST:event_MMenuSairActionPerformed

    private void BtnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovaVendaActionPerformed
        new PDV_VENDA().setVisible(true);
        
    }//GEN-LAST:event_BtnNovaVendaActionPerformed

    private void BtnNovoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoProdActionPerformed
        new CadastrarProd().setVisible(true);
    }//GEN-LAST:event_BtnNovoProdActionPerformed

    private void BtnAtualizarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarFuncActionPerformed
        new EditarFuncionarios().setVisible(true);
    }//GEN-LAST:event_BtnAtualizarFuncActionPerformed

    private void BtnConsAnaliticoRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsAnaliticoRVActionPerformed
        new RelatorioAnalitico().setVisible(true);
    }//GEN-LAST:event_BtnConsAnaliticoRVActionPerformed

    private void BtnConsSinteticoRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsSinteticoRVActionPerformed
        new RelatorioSintetico().setVisible(true);
    }//GEN-LAST:event_BtnConsSinteticoRVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnAtualizarDCli;
    private javax.swing.JMenuItem BtnAtualizarFunc;
    private javax.swing.JMenuItem BtnAtualizarProd;
    private javax.swing.JMenuItem BtnConsAnaliticoRV;
    private javax.swing.JMenuItem BtnConsPCodCli;
    private javax.swing.JMenuItem BtnConsPCodFunc;
    private javax.swing.JMenuItem BtnConsPCodProd;
    private javax.swing.JMenuItem BtnConsPNomeCli;
    private javax.swing.JMenuItem BtnConsPNomeFunc;
    private javax.swing.JMenuItem BtnConsPNomeProd;
    private javax.swing.JMenuItem BtnConsSinteticoRV;
    private javax.swing.JButton BtnNovaVenda;
    private javax.swing.JMenuItem BtnNovoCli;
    private javax.swing.JMenuItem BtnNovoFunc;
    private javax.swing.JMenuItem BtnNovoProd;
    private javax.swing.JMenuItem MMenuSair;
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenu MenuCons;
    private javax.swing.JMenu MenuConsultaCli;
    private javax.swing.JMenu MenuConsultaFunc;
    private javax.swing.JMenu MenuConsultaProd;
    private javax.swing.JMenu MenuFuncionario;
    private javax.swing.JMenu MenuProd;
    private javax.swing.JMenu MenuRelatorioVendas;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
